[workspace]
resolver = "2"
members = [
    "contracts/mock-yield-token",
    "contracts/sy-vault",
    "contracts/splitter",
    "contracts/pt-token",
    "contracts/yt-token",
    "contracts/pt-amm",
]

[workspace.dependencies]
soroban-sdk = "27.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
